# Generated by Django 3.2.5 on 2021-07-15 19:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
