# Generated by Django 3.2.5 on 2021-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_ad_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
