# Generated by Django 3.2.5 on 2021-08-03 20:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(default='', verbose_name='Отклик'),
        ),
    ]
