# Generated by Django 3.2.5 on 2021-08-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210803_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='board.ad'),
        ),
    ]
