# Generated by Django 3.2.5 on 2021-08-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_reply_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.ad'),
        ),
    ]
