openapi: 3.0.2
info:
  title: MMORPG board
  version: '0.1'
servers:
  - url: http://127.0.0.1:8000/board/api
    description: development on localhost
paths:
  /token_auth:
    post:
      operationId: getAPItoken
      description: 'Get API token for registered user'
      requestBody:
        description: user credentials
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/UserId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiToken'
          description: ''
  /news/:
    get:
      operationId: listNews
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'
          description: ''
      tags:
      - news
  /news/{id}/:
    get:
      tags:
      - news
      operationId: retrieveNews
      description: ''
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this news.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsDetail'
          description: ''
  /news/create/:
    post:
      tags:
      - news
      description: 'adding new news'
      operationId: addNews
      requestBody:
        description: news create request
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/NewsCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsDetail'
          description: ''
      security:
        - app_id: []
components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        header:
          type: string
        creation_time:
          type: string
          format: date-time
    NewsCreate:
      type: object
      properties:
        header:
          type: string
        news:
          type: string
    NewsDetail:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        header:
          type: string
        news:
          type: string
        creation_time:
          type: string
          format: date-time
    AdList:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
        category_id:
          type: string
        header:
          type: string
        creation_time:
          type: string
          format: date-time
    ApiToken:
      type: object
      properties:
        token:
          type: string
    UserId:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
  securitySchemes:
    app_id:
      type: apiKey
      name: Authorization
      description: API key to authorize
      in: header
security:
  - app_id: []
