openapi: 3.0.2
info:
  title: MMORPG board
  version: '0.1'
servers:
  - url: http://127.0.0.1:8000/board/api
    description: development on localhost
paths:
  /token_auth:
    post:
      operationId: getAPItoken
      description: 'Get API token for registered user'
      requestBody:
        description: user credentials
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/UserId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiToken'
          description: ''
  /news/:
    get:
      operationId: listNews
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'
          description: ''
      tags:
      - news
  /news/{id}/:
    get:
      tags:
      - news
      operationId: retrieveNews
      description: ''
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this news.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsDetail'
          description: ''
  /news/{id}/mailing:
    post:
      tags:
      - news
      operationId: mailingNews
      description: 'Mailing current news'
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this news.
        schema:
          type: integer
      responses:
        '200':
          description: News sended
  /news/create/:
    post:
      tags:
      - news
      description: 'adding new news'
      operationId: addNews
      requestBody:
        description: news create request
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/NewsCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsDetail'
          description: ''
      security:
        - app_id: []
  /news/{id}/edit:
    patch:
      tags:
      - news
      description: Edit news
      operationId: updateNews
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this news.
        schema:
          type: integer
      requestBody:
        description: news edit request
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/NewsCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsDetail'
          description: ''
      security:
        - app_id: []
  /news/{id}/delete:
    delete:
      tags:
      - news
      description: Delete news
      operationId: deleteNews
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this news.
        schema:
          type: integer
      responses:
        '204':
          description: Deleted successfully
      security:
        - app_id: []
  /ad/:
    get:
      tags:
      - ad
      operationId: listAd
      description: list of all ads
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdList'
          description: ''
  /ad/{id}/:
    get:
      tags:
      - ad
      operationId: retrieveAd
      description: get ad with id
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this ad
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDetail'
          description: ''
  /ad/create/:
    post:
      tags:
      - ad
      description: adding new ad
      operationId: addAd
      requestBody:
        description: ad create request
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AdCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDetail'
          description: ad successfully created
      security:
        - app_id: []
  /ad/{id}/edit:
    patch:
      tags:
      - ad
      description: Edit ad
      operationId: updateAd
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this ad.
        schema:
          type: integer
      requestBody:
        description: ad edit request
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AdCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDetail'
          description: Ad succefffully changed
      security:
        - app_id: []
  /ad/{id}/delete:
    delete:
      tags:
      - ad
      description: Delete ad
      operationId: deleteAd
      parameters:
      - name: id
        required: true
        in: path
        description: A unique integer value identifying this ad.
        schema:
          type: integer
      responses:
        '204':
          description: Deleted successfully
      security:
        - app_id: []
  /reply/:
    get:
      tags:
      - reply
      description: Current user replies list
      operationId: listReply
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReplyList'
          description: ''
components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
          format: email
        header:
          type: string
        creation_time:
          type: string
          format: date-time
    NewsCreate:
      type: object
      properties:
        header:
          type: string
        news:
          type: string
    NewsDetail:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
          format: email
        header:
          type: string
        news:
          type: string
        creation_time:
          type: string
          format: date-time
    AdList:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
          format: email
        category_id:
          type: string
        header:
          type: string
        creation_time:
          type: string
          format: date-time
    AdDetail:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
          format: email
        category_id:
          type: string
        header:
          type: string
        ad:
          type: string
        creation_time:
          type: string
          format: date-time
    AdCreate:
      type: object
      properties:
        category_id:
          type: string
        header:
          type: string
        ad:
          type: string
    ReplyList:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
          format: email
        ad_id:
          type: string
        reply:
          type: string
        creation_time:
          type: string
          format: date-time
        is_approved:
          type: boolean
    ApiToken:
      type: object
      properties:
        token:
          type: string
    UserId:
      type: object
      properties:
        user_id:
          type: string
          format: email
        password:
          type: string
  securitySchemes:
    app_id:
      type: apiKey
      name: Authorization
      description: API key to authorize
      in: header
security:
  - app_id: []
